name = "Fakerjl"
uuid = "59bbcd92-9ea0-11ea-1f68-61ee4b7b554c"
authors = ["osman tamer"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
